"""DIMER inference and bounded-adaptation package for the pinned ZoeDepth checkpoint."""

from .pipeline import (
    DEFAULT_WEIGHTS_DIR,
    DELTA_THRESHOLD,
    DEPTH_KIND,
    DEPTH_RANGES_M,
    DEPTH_UNIT,
    FLIP_AUGMENTATION,
    INPUT_SCHEMA,
    MAX_ASPECT_RATIO,
    MAX_IMAGE_SIDE,
    MIN_IMAGE_SIDE,
    MODEL_ID,
    MODEL_KEY,
    MODEL_LICENSE,
    MODEL_REVISION,
    ZoeDepthMetricPipeline,
    abs_rel,
    delta1,
    evaluation_report,
    stage_missing_files,
    validate_depth_dataset,
    validate_image,
    validate_inputs,
    verify_snapshot,
)

__all__ = [
    "DEFAULT_WEIGHTS_DIR",
    "DELTA_THRESHOLD",
    "DEPTH_KIND",
    "DEPTH_RANGES_M",
    "DEPTH_UNIT",
    "FLIP_AUGMENTATION",
    "INPUT_SCHEMA",
    "MAX_ASPECT_RATIO",
    "MAX_IMAGE_SIDE",
    "MIN_IMAGE_SIDE",
    "MODEL_ID",
    "MODEL_KEY",
    "MODEL_LICENSE",
    "MODEL_REVISION",
    "ZoeDepthMetricPipeline",
    "abs_rel",
    "delta1",
    "evaluation_report",
    "stage_missing_files",
    "validate_depth_dataset",
    "validate_image",
    "validate_inputs",
    "verify_snapshot",
]
